### ISSUE TITLE
播放RTSP流閃退

### ISSUE THREAD

**Issue by manfeng** [CainKernel/CainPlayer#14]
03-20 14:23:52.908 11810-11810/com.cgfay.cainplayer E/Minikin: Could not get cmap table size!
03-20 14:23:52.912 11810-11828/com.cgfay.cainplayer E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
03-20 14:23:56.362 11810-11958/com.cgfay.cainplayer E/CainPlayer: rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov: Protocol not found
03-20 14:23:56.364 11810-11959/com.cgfay.cainplayer E/CainPlayer: Metadata could not be retrieved
03-20 14:23:56.365 11810-11959/com.cgfay.cainplayer E/AndroidRuntime: FATAL EXCEPTION: Thread-6
    Process: com.cgfay.cainplayer, PID: 11810
    java.io.IOException: setDataSource failed.: status = 0xFFFFFFFF
        at com.cgfay.media.CainMediaMetadataRetriever.setDataSource(Native Method)
        at com.cgfay.cainplayer.activity.AVMediaPlayerActivity$6.run(AVMediaPlayerActivity.java:172)
        at java.lang.Thread.run(Thread.java:784)

**Comment by CainKernel** [comment]
这个应该是无限缓冲区的问题。我得代码里面对网络流默认开了无限缓冲区的编制，没限制内存大小的。你去看PlayState对象里面的标志。



发自我的小米手机
在 maple <notifications@github.com>，2019年3月20日 下午2:25写道：

03-20 14:23:52.908 11810-11810/com.cgfay.cainplayer E/Minikin: Could not get cmap table size!
03-20 14:23:52.912 11810-11828/com.cgfay.cainplayer E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
03-20 14:23:56.362 11810-11958/com.cgfay.cainplayer E/CainPlayer: rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov: Protocol not found
03-20 14:23:56.364 11810-11959/com.cgfay.cainplayer E/CainPlayer: Metadata could not be retrieved
03-20 14:23:56.365 11810-11959/com.cgfay.cainplayer E/AndroidRuntime: FATAL EXCEPTION: Thread-6
Process: com.cgfay.cainplayer, PID: 11810
java.io.IOException: setDataSource failed.: status = 0xFFFFFFFF
at com.cgfay.media.CainMediaMetadataRetriever.setDataSource(Native Method)
at com.cgfay.cainplayer.activity.AVMediaPlayerActivity$6.run(AVMediaPlayerActivity.java:172)
at java.lang.Thread.run(Thread.java:784)

**Comment by manfeng** [comment]
试下了下关闭无限缓冲,还是一样,根据提示应该不是缓冲区的问题,log提示的是协议未找到.
03-20 15:58:06.110 16082-16284/com.cgfay.cainplayer E/CainPlayer: rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov: Protocol not found

**Comment by CainKernel** [comment]
Protocol估计是我得so没有打包进去，你可以编译一个带协议的FFmpeg so替换掉。



发自我的小米手机
在 maple <notifications@github.com>，2019年3月20日 下午4:10写道：

试下了下关闭无限缓冲,还是一样,根据提示应该不是缓冲区的问题,log提示的是协议未找到.
03-20 15:58:06.110 16082-16284/com.cgfay.cainplayer E/CainPlayer: rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov: Protocol not found
